import enum
from _typeshed import Incomplete
from paulie.common.pauli_string_bitarray import PauliString as PauliString
from typing import Generator

class ClassificationException(Exception): ...

class TypeGraph(enum.Enum):
    A = 0
    B1 = 1
    B2 = 2
    B3 = 3
    NONE = 4

class TypeAlgebra(enum.Enum):
    U = 0
    SU = 1
    SP = 2
    SO = 3

class Morph:
    legs: Incomplete
    dependents: Incomplete
    def __init__(self, legs: list[list[PauliString]], dependents: list[PauliString]) -> None: ...
    def is_empty(self) -> bool: ...
    def is_empty_legs(self) -> bool: ...
    def get_vertices(self) -> list[PauliString]: ...
    def get_dependents(self) -> list[PauliString]: ...
    def get_legs(self) -> list[list[PauliString]]: ...
    def counts(self) -> tuple[int, int, int]: ...
    def get_properties(self) -> tuple[TypeGraph, int, int, int]: ...
    def get_type(self) -> TypeGraph: ...
    def get_algebra_properties(self) -> tuple[TypeAlgebra, int, int]: ...
    def check_algebra_properties(self, type_algebra: TypeAlgebra | None = None, nc: int | None = None, size: int | None = None) -> bool: ...
    def gen_independent_pair(self) -> Generator[list[list[PauliString]], None, None]: ...
    def gen_pq(self) -> Generator[dict[str, list[PauliString] | int], None, None]: ...
    def gen_generators(self) -> Generator[list[list[PauliString]], None, None]: ...

class Classification:
    morphs: set[Morph]
    def __init__(self) -> None: ...
    def add(self, morph: Morph) -> None: ...
    def get_morphs(self) -> set[Morph]: ...
    def get_algebra(self) -> str: ...
    def contains_algebra(self, algebra: str) -> bool: ...
    def is_algebra(self, algebra: str) -> bool: ...
    def get_subalgebras(self, algebra: str | None = None) -> list[str]: ...
    def get_vertices(self) -> list[PauliString]: ...
    def get_dependents(self) -> list[PauliString]: ...
    def get_isomorphisms(self) -> dict[str, str]: ...
    def get_isomorphism(self, algebra: str) -> str | None: ...
    def get_dla_dim(self) -> int: ...
    def gen_generators(self) -> Generator[list[list[PauliString]], None, None]: ...
