from _typeshed import Incomplete
from paulie.classifier.classification import Morph
from paulie.common.pauli_string_bitarray import PauliString as PauliString
from typing import Self

class AppendedException(Exception): ...
class CheckAppendedException(Exception): ...
class DependentException(Exception): ...
class NotConnectedException(Exception): ...
class RaiseException(Exception): ...
class MorphFactoryException(Exception): ...

class MorphFactory:
    legs: Incomplete
    lighting: Incomplete
    delayed_vertices: Incomplete
    dependents: Incomplete
    is_check: bool
    def __init__(self) -> None: ...
    def set_lighting(self, lighting: PauliString) -> None: ...
    def get_lighting(self) -> PauliString: ...
    def get_morph(self) -> Morph: ...
    def lit(self, lighting: PauliString, vertex: PauliString) -> PauliString: ...
    def get_lits(self, lighting: PauliString, vertices: list[PauliString] = None) -> list[PauliString]: ...
    def is_empty(self) -> bool: ...
    def is_empty_legs(self) -> bool: ...
    def find(self, v: PauliString) -> tuple[int, int]: ...
    def is_included(self, v: PauliString) -> bool: ...
    def get_vertices(self) -> list[PauliString]: ...
    def get_center(self) -> PauliString | None: ...
    def set_center(self, v: PauliString) -> None: ...
    def get_long_leg(self) -> list[PauliString]: ...
    def get_one_vertex(self) -> PauliString: ...
    def get_one_vertices(self) -> list[PauliString]: ...
    def get_pq(self, lighting: PauliString) -> tuple[PauliString | None, PauliString | None]: ...
    def get_two_legs(self) -> list[tuple[PauliString, PauliString]]: ...
    def get_count_two_legs(self) -> int: ...
    def is_two_leg(self) -> bool: ...
    def get_long_legs(self) -> list[list[PauliString]]: ...
    def append(self, v: PauliString, lit: PauliString) -> None: ...
    def append_to_two_center(self, lighting: PauliString) -> None: ...
    def check_dependency_one_leg(self, lighting: PauliString) -> None: ...
    def append_to_center(self, lighting: PauliString) -> None: ...
    def remove(self, v: PauliString) -> None: ...
    def replace(self, v: PauliString, v_new: PauliString) -> None: ...
    def get_lit_indexes(self, vertices: list[PauliString], lits: list[PauliString]) -> list[int]: ...
    def append_delayed(self, v: PauliString) -> None: ...
    def restore_delayed(self, vertices: list[PauliString]) -> list[PauliString]: ...
    def build(self, generators: list[PauliString]) -> Self: ...
    def is_eq(self, legs: list[list[PauliString]], generators: list[PauliString]) -> bool: ...
    def select_dependents(self, legs: list[list[PauliString]], generators: list[PauliString]) -> list[PauliString]: ...
