from paulie.common.pauli_string_bitarray import PauliString as PauliString
from paulie.common.pauli_string_collection import PauliStringCollection as PauliStringCollection
from paulie.helpers.recording import RecordGraph as RecordGraph

def plot_graph(vertices: list[str], edges: list[tuple[str, str]], edge_labels: dict[tuple[str, str], str] = None) -> None: ...
def plot_graph_by_nodes(nodes: PauliStringCollection, commutators: PauliStringCollection | list[PauliString] = None) -> None: ...
def animation_graph(record: RecordGraph, interval: int = 1000, repeat: bool = False, storage: dict[str, str] = None) -> None: ...
