import numpy as np
from _typeshed import Incomplete
from paulie.common.pauli_string_bitarray import PauliString

class FrameGraph:
    vertices: Incomplete
    edges: Incomplete
    edge_labels: Incomplete
    def __init__(self, vertices: list[str], edges: list[tuple[str, str]], edge_labels: dict[tuple[str, str], str] = None) -> None: ...
    def get_graph(self) -> tuple[list[str], list[tuple[str, str]], dict[tuple[str, str], str]]: ...

class FrameRecord:
    graph: Incomplete
    lighting: Incomplete
    lits: Incomplete
    p: Incomplete
    q: Incomplete
    removing_vertices: Incomplete
    replacing_vertices: Incomplete
    dependent: Incomplete
    title: Incomplete
    contracting: Incomplete
    appending: Incomplete
    init: Incomplete
    def __init__(self, graph: FrameGraph = None, lighting: PauliString = None, appending: PauliString = None, contracting=..., lits: list[PauliString] = None, p: PauliString = None, q: PauliString = None, removing_vertices: PauliString = None, replacing_vertices: list[PauliString] = None, dependent: PauliString = None, title: str = None, init: bool = False) -> None: ...
    def get_graph(self) -> tuple[list[str], list[tuple[str, str]], dict[tuple[str, str], str]]: ...
    def get_lighting(self) -> str: ...
    def get_title(self) -> str: ...
    def is_appending(self) -> bool: ...
    def get_is_appending(self, vertex: str) -> bool: ...
    def get_is_contracting(self, vertex: str) -> bool: ...
    def get_is_p(self, vertex: str) -> bool: ...
    def get_is_q(self, vertex: str) -> bool: ...
    def get_is_dependent(self, vertex: str) -> bool: ...
    def get_is_lits(self, vertex: str) -> bool: ...
    def is_removing(self) -> bool: ...
    def get_is_removing(self, vertex: str) -> bool: ...
    def get_is_replacing(self, vertex: str) -> bool: ...
    def get_init(self) -> bool: ...

class RecordGraph:
    frames: FrameRecord
    positions: Incomplete
    x_position_lighting: int
    def __init__(self) -> None: ...
    def append_frame(self, frame: FrameRecord) -> None: ...
    def append(self, graph: FrameGraph = None, lighting: PauliString = None, appending: PauliString = None, contracting: PauliString = None, lits: list[PauliString] = None, p: PauliString = None, q: PauliString = None, removing_vertices: list[PauliString] = None, replacing_vertices: list[PauliString] = None, dependent: PauliString = None, title: str = None, init: bool = False) -> None: ...
    def get_frame(self, index: int) -> FrameRecord: ...
    def clear(self) -> None: ...
    def get_size(self) -> int: ...
    def get_graph(self, index) -> tuple[list[str], list[tuple[str, str]], dict[tuple[str, str], str]] | None: ...
    def get_is_prev(self, index: int) -> bool: ...
    def set_positions(self, positions: dict[str, np.array]) -> None: ...
    def get_positions(self) -> dict[str, np.array]: ...
    def set_x_position_lighting(self, x_position_lighting: int) -> None: ...
    def get_x_position_lighting(self) -> int: ...

def recording_graph(record: RecordGraph, collection: list[PauliString] = None, lighting: PauliString = None, appending: PauliString = None, contracting: PauliString = None, lits: list[PauliString] = None, p: PauliString = None, q: PauliString = None, removing_vertices: list[PauliString] = None, replacing_vertices: list[PauliString] = None, dependent: PauliString = None, title: str = None, init: str = False) -> None: ...
