r"""
Defining-representation matrix bases for the classified dynamical Lie algebra.

``get_algebra`` (see :mod:`paulie.classifier.classification`) names the dynamical
Lie algebra generated by a set of Pauli strings as one of the canonical families
of the Pauli-DLA classification (:cite:t:`Aguilar_2024`); the ``so``, ``su``,
``sp`` and ``u(1)`` realization is tabulated in :cite:t:`Wiersema_2024`. The label
fixes the family and a size parameter, but
it is a name, not a usable object. This module instantiates the named algebra as a
concrete basis of operators in its defining representation, partitioned by direct
summand, so it can be fed to anything algebraic downstream (dimension checks,
structure constants, a Cartan-decomposition pipeline).

The output is fully determined by the classification, so the construction is
table-driven: there is no input-dependent computation beyond reading the
``(family, multiplicity, size)`` of each canonical summand.

Conventions (fixed and documented so downstream consumers get a stable basis)
-----------------------------------------------------------------------------
Every generator is anti-Hermitian, matching the skew-Hermitian convention of a
dynamical Lie algebra (``i`` times a Hermitian observable). Per family:

``so(N)``   real antisymmetric, the standard basis :math:`\{E_{ij} - E_{ji} :
            1 \le i < j \le N\}` in lexicographic ``(i, j)`` order. Shape
            ``(N(N-1)/2, N, N)``, dtype ``float64``. A real antisymmetric matrix
            is anti-Hermitian.

``su(N)``   traceless anti-Hermitian, the generalized Gell-Mann basis times
            ``i``, in the order (a) symmetric off-diagonal ``i(E_ij + E_ji)``,
            (b) antisymmetric off-diagonal ``E_ij - E_ji``, (c) diagonal
            ``i * sqrt(2/(l(l+1))) * diag(1,...,1,-l,0,...)`` for ``l = 1..N-1``.
            Uniformly normalized to ``Tr(M_a^\dagger M_b) = 2 \delta_{ab}``.
            Shape ``(N^2-1, N, N)``, dtype ``complex128``.

``sp(M)``   the COMPACT real form usp(2M), NOT the split form sp(2M, R). The
            Pauli generators are Hermitian, so the dynamical Lie algebra sits in
            ``u(2^n)`` and every element is anti-Hermitian; the symplectic summand
            is therefore the compact form a KAK / Cartan pipeline needs. Matrices
            are ``2M x 2M`` anti-Hermitian ``X`` obeying ``X^T J + J X = 0`` with
            ``J = [[0, I_M], [-I_M, 0]]``, parametrized as
            ``X = [[A, B], [-conj(B), conj(A)]]`` with ``A`` anti-Hermitian
            (``M x M``) and ``B`` complex symmetric. The label argument ``M`` is
            the half-dimension: PauLie's ``sp(M)`` is this ``usp(2M)``, matching
            its own exceptional isomorphisms (``sp(1)`` is ``usp(2)``, isomorphic
            to ``su(2)``; ``sp(2)`` is ``usp(4)``, isomorphic to ``so(5)``). Shape
            ``(M(2M+1), 2M, 2M)``, dtype ``complex128``.

``u(1)``    the single generator ``[[i]]``. Shape ``(1, 1, 1)``, dtype
            ``complex128``.

Direct sums
-----------
A classified algebra is in general a direct sum :math:`\bigoplus_s \mathfrak g_s`.
Its defining representation acts on the direct sum of the per-summand spaces, so a
basis element is an operator on the WHOLE space, block-diagonal with one summand's
block filled and zeros elsewhere. The per-summand bases above are therefore
embedded block-diagonally into the common space rather than returned at their
native block size: the union of all returned matrices is a genuine basis of the
direct sum (it is anti-Hermitian, linearly independent, closed under the
commutator, and reaches every element of the algebra), not a pile of unrelated
blocks. The result keeps the summands separated as a list, one array per summand,
ordered deterministically by ``(family, size)`` so the partition stays recoverable
and the ordering is reproducible (the classification stores summands in a set).
For a single-summand algebra the common space equals the block, so the basis is
returned at its native size.

References
----------
.. bibliography::
   :filter: False

   Aguilar_2024
   Wiersema_2024
"""
from __future__ import annotations

import numpy as np


def so_basis(n: int) -> np.ndarray:
    r"""Basis of :math:`\mathfrak{so}(n)` in the ``n x n`` real antisymmetric
    defining representation.

    Args:
        n (int): Size of the defining representation.
    Returns:
        np.ndarray: Array of shape ``(n(n-1)/2, n, n)``, dtype ``float64``. The
        standard basis :math:`E_{ij} - E_{ji}` for :math:`i < j` in lexicographic
        order.
    """
    dim = n * (n - 1) // 2
    basis = np.zeros((dim, n, n), dtype=np.float64)
    k = 0
    for i in range(n):
        for j in range(i + 1, n):
            basis[k, i, j] = 1.0
            basis[k, j, i] = -1.0
            k += 1
    return basis


def su_basis(n: int) -> np.ndarray:
    r"""Basis of :math:`\mathfrak{su}(n)` in the ``n x n`` traceless
    anti-Hermitian defining representation.

    The generalized Gell-Mann matrices times ``i``. Uniformly normalized to
    :math:`\mathrm{Tr}(M_a^\dagger M_b) = 2\,\delta_{ab}`.

    Args:
        n (int): Size of the defining representation.
    Returns:
        np.ndarray: Array of shape ``(n^2-1, n, n)``, dtype ``complex128``,
        ordered (a) symmetric off-diagonal, (b) antisymmetric off-diagonal,
        (c) diagonal.
    """
    dim = n * n - 1
    basis = np.zeros((dim, n, n), dtype=np.complex128)
    k = 0
    # (a) symmetric off-diagonal:  i (|i><j| + |j><i|)
    for i in range(n):
        for j in range(i + 1, n):
            basis[k, i, j] = 1j
            basis[k, j, i] = 1j
            k += 1
    # (b) antisymmetric off-diagonal:  |i><j| - |j><i|
    for i in range(n):
        for j in range(i + 1, n):
            basis[k, i, j] = 1.0
            basis[k, j, i] = -1.0
            k += 1
    # (c) diagonal:  i sqrt(2/(l(l+1))) diag(1,...,1,-l,0,...)
    for ell in range(1, n):
        scale = np.sqrt(2.0 / (ell * (ell + 1)))
        for i in range(ell):
            basis[k, i, i] = 1j * scale
        basis[k, ell, ell] = -1j * ell * scale
        k += 1
    return basis


def usp_basis(half_dim: int) -> np.ndarray:
    r"""Basis of the compact symplectic algebra usp(2M) in its ``2M x 2M``
    anti-Hermitian defining representation.

    These are the anti-Hermitian ``X`` obeying :math:`X^T J + J X = 0` with
    :math:`J = \begin{psmallmatrix} 0 & I_M \\ -I_M & 0 \end{psmallmatrix}`,
    parametrized as :math:`X = \begin{psmallmatrix} A & B \\ -\bar B & \bar A
    \end{psmallmatrix}` with ``A`` anti-Hermitian and ``B`` complex symmetric.
    This is the compact real form (the symplectic Pauli algebra of
    :cite:t:`Aguilar_2024`), not the split form sp(2M, R).

    Args:
        half_dim (int): Half the size of the defining representation; the
            ``sp(M)`` label argument ``M``. Matrices are ``2M x 2M``.
    Returns:
        np.ndarray: Array of shape ``(M(2M+1), 2M, 2M)``, dtype ``complex128``.
        Ordered: the ``A`` block (anti-Hermitian: diagonal, then symmetric and
        antisymmetric off-diagonal), then the ``B`` block (real symmetric, then
        imaginary symmetric).
    """
    m = half_dim
    size = 2 * m
    dim = m * (2 * m + 1)
    basis = np.zeros((dim, size, size), dtype=np.complex128)
    k = 0

    def _set_a(a_block: np.ndarray) -> None:
        nonlocal k
        basis[k, :m, :m] = a_block
        basis[k, m:, m:] = a_block.conj()
        k += 1

    # A block: anti-Hermitian M x M, embedded as diag(A, conj(A)).
    for i in range(m):  # diagonal imaginary
        a = np.zeros((m, m), dtype=np.complex128)
        a[i, i] = 1j
        _set_a(a)
    for i in range(m):
        for j in range(i + 1, m):  # symmetric off-diagonal
            a = np.zeros((m, m), dtype=np.complex128)
            a[i, j] = 1j
            a[j, i] = 1j
            _set_a(a)
            a = np.zeros((m, m), dtype=np.complex128)  # antisymmetric off-diagonal
            a[i, j] = 1.0
            a[j, i] = -1.0
            _set_a(a)

    def _set_b(b_block: np.ndarray) -> None:
        nonlocal k
        basis[k, :m, m:] = b_block
        basis[k, m:, :m] = -b_block.conj()
        k += 1

    # B block: complex symmetric M x M, embedded as [[0, B], [-conj(B), 0]].
    for i in range(m):
        for j in range(i, m):  # real symmetric
            b = np.zeros((m, m), dtype=np.complex128)
            b[i, j] += 1.0
            b[j, i] += 1.0
            _set_b(b)
            _set_b(1j * b)  # imaginary symmetric
    return basis


def u1_basis() -> np.ndarray:
    r"""Basis of :math:`\mathfrak{u}(1)`: the single generator ``[[i]]`` in the
    ``1 x 1`` defining representation.

    Returns:
        np.ndarray: Array of shape ``(1, 1, 1)``, dtype ``complex128``.
    """
    return np.array([[[1j]]], dtype=np.complex128)


# Sort rank per family so a direct sum is returned in a reproducible order
# (the classification stores its canonical summands in a set). Keyed on the
# lower-case family name so this module stays free of any classifier import.
FAMILY_ORDER = {"u": 0, "su": 1, "so": 2, "sp": 3}


def summand_basis(family: str, size: int) -> np.ndarray:
    """Build the native defining-representation basis for one canonical summand.

    The matrices are returned at their native block size (``N x N``), before any
    embedding into a direct-sum space. Use :func:`block_size` for the block
    dimension and :func:`embed_summand_basis` to place a summand into the common
    space of a direct sum.

    Args:
        family (str): Lie-algebra family, one of ``"u"``, ``"su"``, ``"so"``,
            ``"sp"``.
        size (int): The size parameter of the named algebra (the integer in the
            ``get_algebra`` label, e.g. ``5`` for ``so(5)``).
    Returns:
        np.ndarray: Defining-representation basis of shape ``(dim, N, N)``.
    """
    if family == "u":
        if size != 1:
            raise NotImplementedError(
                f"u({size}) is not part of the Pauli DLA classification; "
                "only u(1) appears as a canonical summand."
            )
        return u1_basis()
    if family == "su":
        return su_basis(size)
    if family == "so":
        return so_basis(size)
    if family == "sp":
        return usp_basis(size)
    raise ValueError(f"Unknown Lie algebra family {family!r}")


def block_size(family: str, size: int) -> int:
    """Side length of the defining-representation matrices for one summand.

    This is ``N`` for ``so(N)``/``su(N)``/``u(1)`` and ``2M`` for the compact
    symplectic ``sp(M)`` (whose matrices are ``2M x 2M``).

    Args:
        family (str): Lie-algebra family, one of ``"u"``, ``"su"``, ``"so"``,
            ``"sp"``.
        size (int): The size parameter from the ``get_algebra`` label.
    Returns:
        int: Side length of one defining-representation matrix.
    """
    if family == "sp":
        return 2 * size
    return size


def embed_summand_basis(family: str, size: int, total: int, offset: int) -> np.ndarray:
    """Build one summand's basis embedded block-diagonally into the common space.

    A direct sum acts on the direct sum of the per-summand spaces. Each basis
    element is an operator on the whole ``total x total`` space with this
    summand's block placed at ``[offset:offset+N, offset:offset+N]`` and zeros
    elsewhere, so the union over all summands is a basis of the complete operator
    rather than a pile of native-size blocks.

    Args:
        family (str): Lie-algebra family.
        size (int): The size parameter from the ``get_algebra`` label.
        total (int): Side length of the common direct-sum space.
        offset (int): Index of this summand's block within the common space.
    Returns:
        np.ndarray: Array of shape ``(dim, total, total)`` (or native ``(dim, N,
        N)`` when ``total`` equals the block size, i.e. a single summand).
    """
    native = summand_basis(family, size)
    block = native.shape[1]
    if total == block:
        return native
    embedded = np.zeros((native.shape[0], total, total), dtype=native.dtype)
    embedded[:, offset:offset + block, offset:offset + block] = native
    return embedded
