"""
    Module to compute the average graph complexity of a specified Pauli string with respect to the
    time evolution generated by a given generator set.
"""
import networkx as nx
from paulie.common.pauli_string_collection import PauliStringCollection
from paulie.common.pauli_string_bitarray import PauliString

def average_graph_complexity(generators: PauliStringCollection, p: PauliString) -> float:
    r"""
    Get the average graph complexity of a Pauli string with respect to the time evolution generated
    by a given generator set.

    The average graph complexity :math:`G` can be computed from the commutation graph as

    .. math::

        \mathbb{E}_{U\sim \mu_G}G(U^{\dagger} p U) = \frac{1}{|C_p|}\sum_{q\in C_p}\ell(p,q)

    where :math:`C_p` is the connected component of the commutation graph containing :math:`p` and
    :math:`\ell(p,q)` is the shortest path length between :math:`p` and :math:`q` in the commutation
    graph.

    (arXiV:2502.16404)

    Args:
        generators (PauliStringCollection): Generating set of the time evolution.
        p (PauliString): Pauli string to compute the average graph complexity of.
    Returns:
        float: Average graph complexity of `p` with respect to the time evolution generated by
        `generators`.
    """
    # Get commutator graph
    vertices, edges = generators.get_commutator_graph()
    # Construct graph in NetworkX
    graph = nx.Graph()
    graph.add_nodes_from(vertices)
    graph.add_edges_from(edges)
    # Get connected component containing p
    subgraph = graph.subgraph(nx.node_connected_component(graph, str(p)))
    # Return a dict of shortest path lengths to all nodes in connected component from p
    spl = nx.shortest_path_length(subgraph, source=str(p))
    # Sum the path lengths and divide by connected component size to obtain average graph complexity
    return sum(spl.values()) / subgraph.number_of_nodes()
