"""
Reachability check - module under development
"""
import numpy as np
from scipy.linalg import block_diag
from paulie.common.pauli_string_collection import PauliStringCollection


def is_in_so(a: np.ndarray) -> bool:
    """
    Check if matrix is in SO.

    Args:
        a: Matrix.
    Returns:
        True if a is in SO.
    """
    return a.dot(a.T) == np.eye(a.shape)


def is_in_sp(a: np.ndarray) -> bool:
    """
    Check if matrix is in Sp.

    Args:
        a: Matrix.
    Returns:
        True if a is in Sp.
    """
    d = a.shape[0]
    j = np.fliplr(block_diag(np.eye(d // 2), np.eye(d // 2)))
    return a.conj() @ j @ a == j


def reachable(u: np.ndarray, generators: PauliStringCollection) -> bool | None:
    """
    Whether a unitary is reachable from the given generators.

    Args:
        u: Unitary as a numpy array.
        generators: Collection of Pauli strings.
    Returns:
        True if reachable, None if the case is not yet handled.
    Raises:
        ValueError: If the unitary dimension exceeds the generator dimension.
    """
    if u.shape[0] > generators.get_len():
        raise ValueError(
            "Unitary cannot be generated by generators of smaller dimensions"
        )
    classification = generators.get_class()
    if classification.is_algebra("su"):
        return True
    if classification.is_algebra("so") and is_in_so(u):
        return True
    if classification.is_algebra("sp") and is_in_sp(u):
        return True
    # the case of direct sum has to be worked out in detail
    return None
