"""
Test classification of dynamical Lie algebras generated by 2-local Pauli
interactions on open spin chains.
"""
from operator import itemgetter
from typing import Any
from unittest.mock import patch, MagicMock
import pytest
import numpy as np
from paulie import (
    G_LIE,
    two_local_algebras,
    get_pauli_string as p,
)
from paulie.classifier.classification import Classification, TypeAlgebra

# System sizes at which the low-rank-compatible a-type / mixed equivalences
# of Theorem I.1 agree through `is_algebra`.
N_FOR_EQUIVALENCE = [3, 4, 5, 6, 7, 8]

# System sizes used for the explicit `is_algebra` checks of every algebra.
N_FOR_EXPLICIT = [3, 4, 5, 6, 7, 8, 9, 10]

A_TYPE_NAMES = [f"a{i}" for i in range(23)]
B_TYPE_NAMES = ["b0", "b1", "b2", "b3", "b4"]
SMALL_N_ALGEBRA_OVERRIDES = {"a11": "so(7)", "a12": "sp(4)", "a17": "sp(4)"}


# ---------------------------------------------------------------------------
# Equivalences
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("n", N_FOR_EQUIVALENCE)
@pytest.mark.parametrize(
    "generators_to_compare",
    [
        # Examples from Wiersema et al. 2024
        ([["XY", "XZ"], ["IX", "XY"]]),                            # Example III.1
        ([["XX", "YZ"], ["YY", "ZX"]]),                            # Example III.4
        ([["ZZ", "YX", "XY"],
          ["XX", "YZ", "ZY"],
          ["YY", "ZX", "XZ"]]),                                    # Example III.5
        # Isomorphism classes from Theorem I.1 (open boundary)
        (itemgetter("a2", "a4")(G_LIE)),                           # so(n) + so(n)
        (itemgetter("a6", "a7", "a10")(G_LIE)),                    # n-parity dependent
        (itemgetter("a13", "a20", "a15")(G_LIE)),                  # su(2^(n-1)) + su(2^(n-1))
    ],
)
def test_multiple_algebra_equivalences(
    generators_to_compare: Any, n: int
) -> None:
    """Each inner list should generate the same Lie algebra at dimension n."""
    algebras = [p(gen_set, n=n) for gen_set in generators_to_compare]
    algebra_names = [algebra.get_algebra() for algebra in algebras]
    assert all(algebra.is_algebra(algebra_names[0]) for algebra in algebras), (
        f"Expected isomorphic algebras at n={n}, got {algebra_names}"
    )


@pytest.mark.parametrize("n", [4, 5, 6, 7, 8])
@pytest.mark.parametrize(
    "generators_to_compare",
    [
        itemgetter("a11", "a16")(G_LIE),
        itemgetter("a12", "a17", "a18", "a19", "a21", "a22")(G_LIE),
    ],
)
def test_large_system_algebra_equivalences(
    generators_to_compare: Any, n: int
) -> None:
    """Families with finite-size exceptions agree from n = 4 onward."""
    algebra = [p(gen_set, n=n).get_algebra() for gen_set in generators_to_compare]
    assert all(a == algebra[0] for a in algebra)


# ---------------------------------------------------------------------------
# Explicit tabulated algebras: a-type
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("n", N_FOR_EXPLICIT)
@pytest.mark.parametrize("name", A_TYPE_NAMES)
def test_a_type_explicit_algebras(name: str, n: int) -> None:
    """Every a-type generator set produces its tabulated Lie algebra.

    Covers the period-dependent families a3 (n mod 8), a5 (n mod 6)
    and a6/a7/a10 (n parity) across the range of n.
    """
    expected = (
        SMALL_N_ALGEBRA_OVERRIDES[name]
        if n == 3 and name in SMALL_N_ALGEBRA_OVERRIDES
        else two_local_algebras(n)[name]
    )
    assert p(G_LIE[name], n=n).is_algebra(expected), (
        f"{name} at n={n}: expected {expected}"
    )


# ---------------------------------------------------------------------------
# Explicit tabulated algebras: b-type
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("n", N_FOR_EXPLICIT)
@pytest.mark.parametrize("name", B_TYPE_NAMES)
def test_b_type_explicit_algebras(name: str, n: int) -> None:
    """Every b-type generator set produces its tabulated Lie algebra.

    The five b-type DLAs (b0, ..., b4) are pairwise non-isomorphic in
    Theorem I.1, so each is checked directly against its closed-form
    expression at several system sizes.
    """
    expected = two_local_algebras(n)[name]
    assert p(G_LIE[name], n=n).is_algebra(expected), (
        f"{name} at n={n}: expected {expected}"
    )


# ---------------------------------------------------------------------------
# Small-system examples from the paper (n in {2, 3})
# ---------------------------------------------------------------------------
def test_explicit_algebras_small_n() -> None:
    """Paper examples at the small system sizes not covered above."""
    assert p(["XX", "YY", "ZZ", "ZY"]).is_algebra("u(1)+2*su(2)")  # Example III.8
    assert p(["XY"]).is_algebra("u(1)")                            # Example I.4
    assert p(["XY"], n=3).is_algebra("so(3)")


@pytest.mark.parametrize(
    ("algebra", "isomorphism"),
    [
        ("sp(1)", "su(2)"),
        ("so(5)", "sp(2)"),
        ("so(6)", "su(4)"),
        ("2*sp(1)", "2*su(2)"),
        ("3*so(5)", "3*sp(2)"),
        ("4*so(6)", "4*su(4)"),
    ],
)
def test_get_isomorphism(algebra: str, isomorphism: str) -> None:
    """Low-rank isomorphisms also preserve algebra multiplicity."""
    assert Classification().get_isomorphism(algebra) == isomorphism


@pytest.mark.parametrize(
    ("canonical", "isomorphic"),
    [("su(2)", "sp(1)"), ("sp(2)", "so(5)"), ("su(4)", "so(6)"), ("2*su(2)", "so(4)")],
)
def test_is_algebra_isomorphism_is_symmetric(canonical: str, isomorphic: str) -> None:
    """Comparison accepts either side of each low-rank isomorphism."""
    classification = Classification()
    with patch.object(classification, "get_algebra", return_value=canonical):
        assert classification.is_algebra(isomorphic)
    with patch.object(classification, "get_algebra", return_value=isomorphic):
        assert classification.is_algebra(canonical)


# ---------------------------------------------------------------------------
# Basis generation: get_algebra_basis and helpers
# ---------------------------------------------------------------------------
def test_aggregate_components() -> None:
    """Helper _aggregate_components groups identical morphs correctly."""
    classification = Classification()
    
    morph1 = MagicMock()
    morph1.get_algebra_properties.return_value = (TypeAlgebra.SU, 1, 4) # su(4)
    morph2 = MagicMock()
    morph2.get_algebra_properties.return_value = (TypeAlgebra.SU, 2, 4) # 2*su(4), multiplicity 2
    morph3 = MagicMock()
    morph3.get_algebra_properties.return_value = (TypeAlgebra.U, 1, 1) # u(1)

    classification.add(morph1)
    classification.add(morph2)
    classification.add(morph3)

    components = classification._aggregate_components()
    
    # We expect total multiplicity of 3 for su(4), and 1 for u(1)
    expected = {(3, 'su', 4), (1, 'u', 1)}
    assert set(components) == expected


@pytest.mark.parametrize(
    ("alg_type", "param", "expected_rep_dim"),
    [
        ("su", 4, 4), # N=2
        ("so", 3, 3), 
        ("sp", 2, 4), # rep_dim is 2*param
        ("u", 1, 1), 
    ],
)
def test_generate_sub_basis(alg_type: str, param: int, expected_rep_dim: int) -> None:
    """Helper _generate_sub_basis routes to the correct generator."""
    classification = Classification()
    basis, rep_dim = classification._generate_sub_basis(alg_type, param)
    
    assert rep_dim == expected_rep_dim
    assert isinstance(basis, list)
    if alg_type == "u":
        assert len(basis) == 1
        assert np.array_equal(basis[0], np.array([[1j]], dtype=complex))
    else:
        for mat in basis:
            assert isinstance(mat, np.ndarray)
            assert mat.shape == (rep_dim, rep_dim)


def test_generate_sub_basis_invalid_type() -> None:
    """Helper _generate_sub_basis raises ValueError on unknown algebra type."""
    classification = Classification()
    with pytest.raises(ValueError, match="Unknown algebra type: invalid"):
        classification._generate_sub_basis("invalid", 1)


def test_get_algebra_basis() -> None:
    """Main function get_algebra_basis assembles block-diagonal matrices."""
    classification = Classification()
    
    mock_components = [(2, "su", 2), (1, "u", 1)]
    mock_su_basis = [np.ones((2, 2))]
    mock_u_basis = [np.ones((1, 1))]
    
    with patch.object(
        classification, "_aggregate_components", return_value=mock_components
    ), patch.object(
        classification, "_generate_sub_basis", side_effect=[(mock_su_basis, 2), (mock_u_basis, 1)]
    ):
        basis = classification.get_algebra_basis()
        
        # total_dim = 2 * 2 (for su) + 1 * 1 (for u) = 5
        # The basis should have 3 matrices total (2 from su copies, 1 from u copy)
        assert len(basis) == 3
        
        for mat in basis:
            assert mat.shape == (5, 5)
            assert mat.dtype == complex
            
        # First matrix: ones at block [0:2, 0:2]
        assert np.array_equal(basis[0][0:2, 0:2], np.ones((2, 2)))
        assert np.count_nonzero(basis[0]) == 4
        
        # Second matrix: ones at block [2:4, 2:4]
        assert np.array_equal(basis[1][2:4, 2:4], np.ones((2, 2)))
        assert np.count_nonzero(basis[1]) == 4
        
        # Third matrix: ones at block [4:5, 4:5]
        assert np.array_equal(basis[2][4:5, 4:5], np.ones((1, 1)))
        assert np.count_nonzero(basis[2]) == 1
