"""Tests for :meth:`get_algebra_basis` -- the defining-representation matrix
basis of the classified dynamical Lie algebra.

How "it is a basis" is established
----------------------------------
A label like ``"sp(4)"`` is an isomorphism class; what matters is that the
returned matrices form a basis of *the same abstract Lie algebra* as the one
generated by the Pauli strings.  Matching the dimension alone is not sufficient
(non-isomorphic Lie algebras can share a dimension), and checking a defining
condition such as antisymmetry is representation-specific, so neither certifies
the algebra on its own.

Instead we compare the returned basis against the **brute-force Pauli Lie
closure** (the ground truth used in ``docs/examples/benchmark_classification.py``)
through *representation-independent* invariants.  The adjoint representation, and
hence the Killing form, depend only on the abstract Lie algebra, not on the
matrices used to realise it -- so they can be compared even though the closure
lives on :math:`\\mathbb{C}^{2^n}` while the defining rep is :math:`N\\times N`.
For every test case the returned basis and the embedded closure agree on

* the dimension,
* the dimension of the centre (Killing-form nullity),
* the dimension of the semisimple part (Killing-form rank),
* the Lie rank (dimension of a Cartan subalgebra),

which certifies that the returned set spans a Lie algebra isomorphic to the DLA.
The intrinsic invariants are real-form agnostic (the symplectic family is
returned in its split real form, the DLA is compact -- isomorphic over the
complexification), which is exactly what we want here.

Generators and expected labels are taken from the built-in
:data:`paulie.G_LIE` / :func:`paulie.two_local_algebras` tables rather than
hard-coded, and dimensions come from :meth:`get_dla_dim`.
"""
from itertools import product

import numpy as np
import pytest

from paulie import get_pauli_string as p
from paulie.common.two_local_generators import G_LIE, two_local_algebras

TOL = 1e-9
ZERO_EIG_TOL = 1e-6


# --------------------------------------------------------------------------- #
# Real vector-space helpers (a real Lie algebra is a real vector space)
# --------------------------------------------------------------------------- #
def _real_rows(stack: np.ndarray) -> np.ndarray:
    """Real coordinates (Re and Im parts) of every matrix, one row each."""
    flat = stack.reshape(stack.shape[0], -1)
    return np.hstack([flat.real, flat.imag])


def _dim_real_span(stack: np.ndarray) -> int:
    """Dimension of the real span of a stack of matrices."""
    if stack.shape[0] == 0:
        return 0
    return int(np.linalg.matrix_rank(_real_rows(stack), tol=TOL))


def _is_independent(stack: np.ndarray) -> bool:
    """The matrices are linearly independent over the reals."""
    return _dim_real_span(stack) == stack.shape[0]


def _is_closed_under_bracket(stack: np.ndarray) -> bool:
    """Every commutator of basis elements lies in the real span of the basis."""
    base_dim = _dim_real_span(stack)
    brackets = [
        stack[a] @ stack[b] - stack[b] @ stack[a]
        for a in range(stack.shape[0])
        for b in range(a + 1, stack.shape[0])
    ]
    if not brackets:
        return True
    augmented = np.concatenate([stack, np.stack(brackets, axis=0)], axis=0)
    return _dim_real_span(augmented) == base_dim


# --------------------------------------------------------------------------- #
# Intrinsic (representation-independent) Lie-algebra invariants
# --------------------------------------------------------------------------- #
def _adjoint(stack: np.ndarray) -> np.ndarray:
    """Adjoint representation of the Lie algebra spanned by ``stack``.

    Returns ``ad`` of shape ``(d, d, d)`` with ``ad[i, k, j]`` the coefficient of
    basis element ``k`` in ``[e_i, e_j]``.  The adjoint (and the Killing form
    built from it) depends only on the abstract algebra, so it is comparable
    across different matrix representations.
    """
    d = stack.shape[0]
    rows = _real_rows(stack)
    projector = np.linalg.pinv(rows.T)  # (d, 2 N^2): coordinates from a vector
    ad = np.zeros((d, d, d))
    for i in range(d):
        commutators = stack[i] @ stack - stack @ stack[i]   # (d, N, N), index j
        ad[i] = (_real_rows(commutators) @ projector.T).T
    return ad


def _fingerprint(stack: np.ndarray) -> tuple[int, int, int, int]:
    """(dim, centre dim, semisimple dim, Lie rank) of the spanned algebra."""
    dim = stack.shape[0]
    ad = _adjoint(stack)
    killing = np.einsum("ikl,jlk->ij", ad, ad)          # K_ij = tr(ad_i ad_j)
    semisimple = int(np.linalg.matrix_rank(killing))
    centre = dim - semisimple
    generic = np.tensordot(np.random.default_rng(0).standard_normal(dim), ad, axes=(0, 0))
    eigenvalues = np.linalg.eigvals(generic)
    threshold = ZERO_EIG_TOL * max(1.0, float(np.abs(eigenvalues).max(initial=0.0)))
    centraliser = int(np.sum(np.abs(eigenvalues) < threshold))
    return dim, centre, semisimple, centraliser - centre


def _summed_fingerprint(summands: list[np.ndarray]) -> tuple[int, int, int, int]:
    """Invariants of a direct sum add up across its summands."""
    total = (0, 0, 0, 0)
    for summand in summands:
        total = tuple(a + b for a, b in zip(total, _fingerprint(summand)))
    return total  # type: ignore[return-value]


# --------------------------------------------------------------------------- #
# Brute-force Pauli Lie closure -> embedded realisation of the DLA
# --------------------------------------------------------------------------- #
def _lie_closure(collection) -> list:
    """The DLA as Pauli strings, via brute-force commutator enumeration.

    Mirrors ``lie_closure_brute_force`` from the benchmark example; computed
    independently of ``get_dla_dim`` / ``get_algebra_basis``.
    """
    dla = list(collection.get())
    old_len, new_len = 0, len(dla)
    initial_len = new_len
    while new_len > old_len:
        for pw1, pw2 in product(dla[:initial_len], dla[old_len:]):
            if pw1.commutes_with(pw2):
                continue
            com = pw1 @ pw2
            if com not in dla:
                dla.append(com)
        old_len, new_len = new_len, len(dla)
    return dla


def _embedded_algebra(collection) -> np.ndarray:
    """The DLA as anti-Hermitian matrices i*P on the full 2^n Hilbert space."""
    return np.stack([1j * pw.get_matrix() for pw in _lie_closure(collection)], axis=0)


# --------------------------------------------------------------------------- #
# Cases driven by the built-in generator / algebra tables (not hard-coded).
# Each (name, n) is annotated with the canonical type / family it exercises.
# --------------------------------------------------------------------------- #
ISOMORPHISM_CASES = [
    ("a1", 3),    # A   -> so(3)
    ("a1", 4),    # A   -> so(4) = 2*so(3)        (direct sum)
    ("a8", 3),    # B-type -> so(5) = sp(2)        (exceptional iso)
    ("a6", 3),    # -> so(6) = su(4)               (exceptional iso, semisimple)
    ("a9", 4),    # B1  -> sp(4)
    ("a11", 4),   # B2  -> so(16)
    ("a13", 4),   # B3  -> 2*su(8)                 (direct sum)
    ("a1", 2),    # exception -> u(1)              (single Pauli string)
]

# Larger algebras: only the cheap dimension checks (the intrinsic comparison
# above already covers every family at small size).
DIMENSION_CASES = ISOMORPHISM_CASES + [
    ("a12", 4),   # B3  -> su(16)
    ("a0", 4),    # -> 3*u(1)                      (repeated abelian summands)
]


# --------------------------------------------------------------------------- #
# The returned basis is the same abstract algebra as the brute-force closure
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("name, n", ISOMORPHISM_CASES)
def test_basis_is_isomorphic_to_embedded_dla(name, n):
    """Each summand is a Lie algebra, and the whole basis is isomorphic to the
    embedded brute-force closure (matching representation-independent invariants).
    """
    coll = p(G_LIE[name], n=n)
    summands = coll.get_algebra_basis()
    for summand in summands:
        assert _is_independent(summand)
        assert _is_closed_under_bracket(summand)

    assert _summed_fingerprint(summands) == _fingerprint(_embedded_algebra(coll))


# Cases where the analytic ``two_local_algebras`` formula is valid (n >= 3); the
# n = 2 entry of ISOMORPHISM_CASES is the degenerate so(2) = u(1) corner.
@pytest.mark.parametrize("name, n", [c for c in ISOMORPHISM_CASES if c[1] >= 3])
def test_classifier_label_matches_builtin_formula(name, n):
    """The classifier agrees with the built-in analytic algebra table."""
    coll = p(G_LIE[name], n=n)
    assert coll.is_algebra(two_local_algebras(n)[name])


@pytest.mark.parametrize("name, n", DIMENSION_CASES)
def test_total_dimension_matches_closure_and_get_dla_dim(name, n):
    """Total basis size equals both ``get_dla_dim`` and the brute-force closure."""
    coll = p(G_LIE[name], n=n)
    total = sum(summand.shape[0] for summand in coll.get_algebra_basis())
    assert total == coll.get_dla_dim()
    assert total == len(_lie_closure(coll))


# --------------------------------------------------------------------------- #
# Direct-sum structure: one entry per summand, blocks commute
# --------------------------------------------------------------------------- #
def test_summand_count_matches_label():
    """``len(basis)`` equals the number of direct summands in the label."""
    assert len(p(G_LIE["a1"], n=3).get_algebra_basis()) == 1          # so(3)
    assert len(p(G_LIE["a1"], n=4).get_algebra_basis()) == 2          # 2*so(3)
    assert len(p(G_LIE["a13"], n=4).get_algebra_basis()) == 2         # 2*su(8)
    assert len(p(G_LIE["a0"], n=4).get_algebra_basis()) == 3          # 3*u(1)


def test_cross_summand_brackets_vanish():
    """Block-embedding two summands yields commuting blocks: [g_1, g_2] = 0."""
    summands = p(G_LIE["a13"], n=4).get_algebra_basis()
    assert len(summands) == 2
    first, second = summands[0], summands[1]
    size = first.shape[1]
    top = np.zeros((2 * size, 2 * size), dtype=np.complex128)
    top[:size, :size] = first[0]
    bottom = np.zeros((2 * size, 2 * size), dtype=np.complex128)
    bottom[size:, size:] = second[1]
    assert np.allclose(top @ bottom - bottom @ top, 0.0, atol=TOL)


# --------------------------------------------------------------------------- #
# Stable, documented output contract
# --------------------------------------------------------------------------- #
def test_ordering_is_deterministic():
    """Repeated calls return summands in the same order and with the same values."""
    first = p(G_LIE["a13"], n=4).get_algebra_basis()
    second = p(G_LIE["a13"], n=4).get_algebra_basis()
    assert len(first) == len(second)
    for left, right in zip(first, second):
        assert left.shape == right.shape
        assert np.allclose(left, right, atol=TOL)


def test_returned_arrays_are_independent_copies():
    """Mutating a returned summand must not affect a fresh call."""
    basis = p(G_LIE["a1"], n=3).get_algebra_basis()[0]
    basis[0] += 1.0
    fresh = p(G_LIE["a1"], n=3).get_algebra_basis()[0]
    assert not np.allclose(basis[0], fresh[0], atol=TOL)


# --------------------------------------------------------------------------- #
# Builder unit tests: the documented standard-form conventions
# --------------------------------------------------------------------------- #
def test_builders_follow_documented_conventions():
    """The raw builders emit matrices in the documented standard form."""
    from paulie.application.algebra_basis import (
        orthogonal_basis,
        special_unitary_basis,
        symplectic_basis,
        symplectic_form,
        unitary_basis,
    )

    so5 = orthogonal_basis(5)
    assert so5.shape == (10, 5, 5)
    for mat in so5:
        assert np.allclose(mat + mat.T, 0.0, atol=TOL)
        assert np.allclose(mat.imag, 0.0, atol=TOL)

    su3 = special_unitary_basis(3)
    assert su3.shape == (8, 3, 3)
    for mat in su3:
        assert np.allclose(mat + mat.conj().T, 0.0, atol=TOL)
        assert abs(np.trace(mat)) < TOL

    form = symplectic_form(2)
    sp2 = symplectic_basis(2)
    assert sp2.shape == (10, 4, 4)
    for mat in sp2:
        assert np.allclose(mat.T @ form + form @ mat, 0.0, atol=TOL)

    u1 = unitary_basis(1)
    assert u1.shape == (1, 1, 1)
    assert np.allclose(u1[0] + u1[0].conj().T, 0.0, atol=TOL)


def test_symplectic_form_matches_documented_convention():
    """``symplectic_form`` equals the documented J = [[0, I], [-I, 0]]."""
    from paulie.application.algebra_basis import symplectic_form
    for rank in (1, 2, 4):
        eye = np.eye(rank, dtype=np.complex128)
        zero = np.zeros((rank, rank), dtype=np.complex128)
        expected = np.block([[zero, eye], [-eye, zero]])
        assert np.allclose(symplectic_form(rank), expected, atol=TOL)
