"""
Test classification of dynamical Lie algebras generated by 2-local Pauli
interactions on open spin chains.
"""
from operator import itemgetter
from typing import Any
import pytest
from paulie import (
    G_LIE,
    two_local_algebras,
    get_pauli_string as p,
)

# System sizes at which the a-type / mixed equivalences of Theorem I.1 all
# agree through `get_algebra` string comparison.  (n = 3 is excluded
# because a11 = a16 and the ak = su(2^n) family only kick in at n >= 4.)
N_FOR_EQUIVALENCE = [4, 5, 6, 7, 8]

# System sizes used for the explicit `is_algebra` checks of every
# tabulated algebra.  Starts at n = 5 so that the library's canonical
# algebra string matches the tabulated formula without needing any
# small-n Lie-algebra isomorphisms.
N_FOR_EXPLICIT = [5, 6, 7, 8, 9, 10]

A_TYPE_NAMES = [f"a{i}" for i in range(23)]
B_TYPE_NAMES = ["b0", "b1", "b2", "b3", "b4"]


# ---------------------------------------------------------------------------
# Equivalences
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("n", N_FOR_EQUIVALENCE)
@pytest.mark.parametrize(
    "generators_to_compare",
    [
        # Examples from Wiersema et al. 2024
        ([["XY", "XZ"], ["IX", "XY"]]),                            # Example III.1
        ([["XX", "YZ"], ["YY", "ZX"]]),                            # Example III.4
        ([["ZZ", "YX", "XY"],
          ["XX", "YZ", "ZY"],
          ["YY", "ZX", "XZ"]]),                                    # Example III.5
        # Isomorphism classes from Theorem I.1 (open boundary)
        (itemgetter("a2", "a4")(G_LIE)),                           # so(n) + so(n)
        (itemgetter("a11", "a16")(G_LIE)),                         # so(2^n), n >= 4
        (itemgetter("a6", "a7", "a10")(G_LIE)),                    # n-parity dependent
        (itemgetter("a13", "a20", "a15")(G_LIE)),                  # su(2^(n-1)) + su(2^(n-1))
        (itemgetter("a12", "a17", "a18", "a19", "a21", "a22")(G_LIE)),  # su(2^n), n >= 4
    ],
)
def test_multiple_algebra_equivalences(
    generators_to_compare: Any, n: int
) -> None:
    """Each inner list should generate the same Lie algebra at dimension n."""
    algebra = [p(gen_set, n=n).get_algebra() for gen_set in generators_to_compare]
    assert all(a == algebra[0] for a in algebra), (
        f"Expected identical algebras at n={n}, got {algebra}"
    )


# ---------------------------------------------------------------------------
# Explicit tabulated algebras: a-type
# ---------------------------------------------------------------------------
# Consider isomorphisms and improve is_algebra
@pytest.mark.parametrize("n", N_FOR_EXPLICIT)
@pytest.mark.parametrize("name", A_TYPE_NAMES)
def test_a_type_explicit_algebras(name: str, n: int) -> None:
    """Every a-type generator set produces its tabulated Lie algebra.

    Covers the period-dependent families a3 (n mod 8), a5 (n mod 6)
    and a6/a7/a10 (n parity) across the range of n.
    """
    expected = two_local_algebras(n)[name]
    assert p(G_LIE[name], n=n).is_algebra(expected), (
        f"{name} at n={n}: expected {expected}"
    )


# ---------------------------------------------------------------------------
# Explicit tabulated algebras: b-type
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("n", N_FOR_EXPLICIT)
@pytest.mark.parametrize("name", B_TYPE_NAMES)
def test_b_type_explicit_algebras(name: str, n: int) -> None:
    """Every b-type generator set produces its tabulated Lie algebra.

    The five b-type DLAs (b0, ..., b4) are pairwise non-isomorphic in
    Theorem I.1, so each is checked directly against its closed-form
    expression at several system sizes.
    """
    expected = two_local_algebras(n)[name]
    assert p(G_LIE[name], n=n).is_algebra(expected), (
        f"{name} at n={n}: expected {expected}"
    )


# ---------------------------------------------------------------------------
# Small-system examples from the paper (n in {2, 3})
# ---------------------------------------------------------------------------
def test_explicit_algebras_small_n() -> None:
    """Paper examples at the small system sizes not covered above."""
    assert p(["XX", "YY", "ZZ", "ZY"]).is_algebra("u(1)+2*su(2)")  # Example III.8
    assert p(["XY"]).is_algebra("u(1)")                            # Example I.4
    assert p(["XY"], n=3).is_algebra("so(3)")
    # n = 3 is deliberately not swept in the parametrised tests above:
    # e.g. a6(3) ~= su(4) ~= so(6), but is_algebra does not collapse
    # that small-n isomorphism (see comment above A_TYPE tests).