from paulie.common.pauli_string_bitarray import PauliString as PauliString

def get_graph(generators: list[PauliString], commutators: list[PauliString] | None = None, flag_labels: bool = True) -> tuple[list[str], list[tuple[str, str]], dict[tuple[str, str], str]] | tuple[list[str], list[tuple[str, str]]]: ...
