import numpy as np
from bitarray import bitarray
from typing import Generator, Self

class PauliString:
    def __init__(self, n: int | None = None, pauli_str: str | None = None, bits: bitarray | None = None) -> None: ...
    def get_index(self) -> int: ...
    def get_diagonal_index(self) -> int: ...
    def get_weight_in_matrix(self, b_matrix: np.ndarray) -> np.complex128: ...
    def create_instance(self, n: int | None = None, pauli_str: str | None = None) -> PauliString: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> PauliString: ...
    def __setitem__(self, position: int, pauli_string: str | Self) -> None: ...
    def __getitem__(self, position: int) -> PauliString: ...
    def __copy__(self) -> PauliString: ...
    def copy(self) -> PauliString: ...
    def __add__(self, other: object) -> PauliString: ...
    def __or__(self, other: object) -> bool: ...
    def __xor__(self, other: object) -> PauliString | None: ...
    def __matmul__(self, other: object) -> PauliString: ...
    def sign(self, other: PauliString) -> complex: ...
    def complex_conj(self) -> tuple[complex, str | Self]: ...
    def commutes_with(self, other: object) -> bool: ...
    def get_substring(self, start: int, length: int = 1) -> PauliString: ...
    def set_substring(self, start: int, pauli_string: str | PauliString) -> None: ...
    def is_identity(self) -> bool: ...
    def tensor(self, other: Self) -> PauliString: ...
    def multiply(self, other: object) -> PauliString: ...
    def adjoint_map(self, other: object) -> PauliString | None: ...
    def inc(self) -> Self: ...
    def expand(self, n: int) -> PauliString: ...
    def gen_all_pauli_strings(self) -> Generator[PauliString, None, None]: ...
    def get_commutants(self, generators: list[PauliString] | None = None) -> list[PauliString]: ...
    def get_anti_commutants(self, generators: list[PauliString] | None = None) -> list[PauliString]: ...
    def get_nested(self, generators: list[PauliString] | None = None) -> list[tuple[PauliString, PauliString]]: ...
    def get_matrix(self) -> np.ndarray: ...
    def get_count_non_trivially(self) -> int: ...
