from paulie.common.pauli_string_bitarray import PauliString
from paulie.common.pauli_string_collection import PauliStringCollection
from paulie.common.pauli_string_linear import PauliStringLinear
from typing import Generator

def get_identity(n: int) -> PauliString: ...
def get_single(n: int, i: int, label: str) -> PauliString: ...
def get_last(n: int) -> PauliString: ...
def get_pauli_string(o: PauliString | PauliStringCollection, n: int | None = None) -> PauliString | PauliStringLinear | PauliStringCollection: ...

class Used:
    used: set[str]
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def append(self, p: PauliString) -> None: ...
    def is_used(self, p: PauliString) -> bool: ...

def gen_k_local(n: int, p: PauliString, used: Used | None = None) -> Generator[list[PauliString], None, None]: ...
def gen_k_local_generators(n: int, generators: list[str] | list[PauliString] | PauliStringCollection, used: Used | None = None) -> Generator[list[PauliString], None, None]: ...
