from paulie.classifier.classification import Classification
from paulie.common.pauli_string_bitarray import PauliString
from paulie.common.pauli_string_linear import PauliStringLinear
from paulie.helpers.recording import RecordGraph as RecordGraph
from typing import Generator, Self

class PauliStringCollectionException(Exception): ...

class PauliStringCollection:
    nextpos: int
    generators: list[PauliString]
    classification: Classification
    record: RecordGraph
    def __init__(self, generators: list[PauliString] | Self | None = None) -> None: ...
    def get(self) -> list[PauliString]: ...
    def get_len(self) -> int: ...
    def set_record(self, record: RecordGraph) -> None: ...
    def get_record(self) -> RecordGraph: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> PauliString: ...
    def __delitem__(self, key: int) -> PauliString: ...
    def __copy__(self) -> PauliStringCollection: ...
    def copy(self) -> PauliStringCollection: ...
    def __add__(self, p: PauliString) -> PauliStringCollection: ...
    def mul(self, a: Self, b: Self) -> PauliStringCollection: ...
    def __mul__(self, other: Self) -> PauliStringCollection: ...
    def __rmul__(self, other: Self) -> PauliStringCollection: ...
    def expand(self, n: int) -> None: ...
    def append(self, p: PauliString) -> None: ...
    def insert(self, i: int, p: PauliString) -> None: ...
    def remove(self, p: PauliString) -> None: ...
    def index(self, p: PauliString) -> int: ...
    def get_size(self) -> int: ...
    def create_instance(self, n: int | None = None, pauli_str: str | None = None) -> PauliString: ...
    def sort(self) -> Self: ...
    def get_anticommutation_fraction(self) -> float: ...
    def get_pair(self) -> int: ...
    def get_anticommutation_pair(self) -> int: ...
    def get_commutants(self) -> PauliStringCollection: ...
    def get_anti_commutants(self, generators: PauliStringCollection) -> PauliStringCollection: ...
    def get_graph(self, generators: list[PauliString] | PauliStringCollection | None = None) -> tuple[list[str], list[tuple[str, str]], dict[tuple[str, str], str]]: ...
    def get_commutator_graph(self) -> tuple[list[str], list[tuple[str, str]]]: ...
    def get_frame_potential(self) -> int: ...
    def get_subgraphs(self) -> list[PauliStringCollection]: ...
    def classify(self) -> Classification: ...
    def get_class(self) -> Classification: ...
    def get_algebra(self) -> str: ...
    def is_algebra(self, algebra: str) -> bool: ...
    def is_in(self, generators: Self) -> bool: ...
    def is_eq(self, generators: Self) -> bool: ...
    def select_dependents(self, generators: Self) -> bool | PauliStringCollection: ...
    def get_space(self) -> bool | PauliStringCollection: ...
    def gen_generators(self) -> Generator[PauliStringCollection, None, None]: ...
    def get_dla_dim(self) -> int: ...
    def get_dependents(self) -> PauliStringCollection: ...
    def get_independents(self) -> PauliStringCollection: ...
    def get_canonic_vertices(self) -> PauliStringCollection: ...
    def get_canonic_graph(self) -> tuple[list[str], list[tuple[str, str]], dict[tuple[str, str], str]]: ...
    def get_anti_commutates(self, pauli_string: PauliString, generators: PauliStringCollection) -> PauliStringCollection: ...
    def get_commutates(self, pauli_string: PauliString, generators: PauliStringCollection) -> PauliStringCollection: ...
    def get_graph_components(self, graph_type: str = 'anticommutator') -> list['PauliStringCollection']: ...
    def get_symmetries_for_component(self, linear_symmetries: Self) -> list[PauliStringLinear]: ...
    def get_full_quadratic_basis(self, normalized: bool = False) -> list[PauliStringLinear]: ...
    def find(self, pauli_string: PauliString) -> int: ...
    def replace(self, pauli_string: PauliString, new_pauli_string: PauliString) -> None: ...
    def contract(self, pauli_string: PauliString, contracted_pauli_string: PauliString) -> None: ...
    def list_connections(self) -> list[tuple[PauliString, PauliString, int, int]]: ...
    def find_generators_with_connection(self, number_connections: int) -> PauliStringCollection: ...
